version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongP@ssw0rd!"
      MSSQL_PID: "Developer"
    volumes:
      - sql_data:/var/opt/mssql        # Persistencia de datos

volumes:
  sql_data:
