SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Columns_pag_22](
	[ColumnID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre01] [nvarchar](100) NULL,
	[Nombre02] [nvarchar](100) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Columns_pag_22] ADD PRIMARY KEY CLUSTERED 
(
	[ColumnID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
